openapi: 3.0.2
paths:
  /define/question:
    get:
      tags: &a1
        - question
      parameters:
        - name: x-auth-token
          in: header
          required: true
          schema:
            type: string
      operationId: getAllMyQuestions
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    userId:
                      type: number
                    docId:
                      type: number
                    index:
                      type: number
                    description:
                      type: string
                    question:
                      type: string
                    weight:
                      type: number
                    testedTimes:
                      type: number
                    toRefine:
                      type: boolean
                    createdAt:
                      type: string
                    updatedAt:
                      type: string
                  required:
                    - id
                    - userId
                    - docId
                    - index
                    - description
                    - question
                    - weight
                    - testedTimes
                    - toRefine
                    - createdAt
                    - updatedAt
  /ask-gpt:
    get:
      tags: *a1
      parameters:
        - name: x-auth-token
          in: header
          required: true
          schema:
            type: string
        - name: question
          in: query
          required: true
          schema:
            type: string
      operationId: askGpt
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                required:
                  - answer
        "403":
          description: "403"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum:
                      - You're not allowed to access this resource.
                required:
                  - message
info:
  title: My API
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
